name: 'CI/CD'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm init -y
        npm install eslint@latest --save-dev

    - name: Create ESLint config
      run: |
        cat << EOF > eslint.config.js
        import js from '@eslint/js';
        import globals from 'globals';

        export default [
          js.configs.recommended,
          {
            files: ['**/*.js'],
            languageOptions: {
              globals: {
                ...globals.node
              },
              ecmaVersion: 2022
            },
            rules: {
              'quotes': ['error', 'single'],
              'semi': ['error', 'never'],
              'comma-dangle': ['error', 'never'],
              'no-unused-vars': ['error', { 'argsIgnorePattern': '^_' }],
              'object-curly-spacing': ['error', 'always'],
              'key-spacing': ['error', { 'beforeColon': false, 'afterColon': true }],
              'object-shorthand': 'warn',
              'prefer-const': 'error',
              'spaced-comment': ['error', 'always'],
              'quote-props': ['error', 'as-needed'],
              'camelcase': ['error', { 'properties': 'never' }]
            }
          }
        ];
        EOF

    - name: Run ESLint
      run: |
        npx eslint --fix ./secondChance-backend/**/*.js ./sentiment/**/*.js

    - name: Commit linting changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Apply automatic linting fixes" || echo "No changes to commit"
        git push
